
---FIRST PASS THROUGH LOOKING AT TOTAL $$ AMOUNT OF CLAIMS VERSUS FREQUENCY OF CLAIMS
--SOME ACCOUNTS WILL HAVE 20+ CLAIMS DUE TO TOWING COUNTING AS A 'CLAIM'
WITH POLICY_HOLDERS AS
(
  --QQ HOW TO IDENTIFY ONE HH WITH MULTIPLE POLICY NUMBERS
  SELECT  `Policy Number` AS POLICY_NBR
    ,`Original Year` AS START_YR
    ,`Termination Effective Date` AS TERM_DT
    --START DATE
    ,PARSE_DATE('%d-%b-%Y',CONCAT(`Anniversary Effective Date`,"-",`Original Year`)) AS START_DT
    --CREATING NUMBER OF MONTHS POLICY HOLDER HAS HAD A GIVEN POLICY
    ,SAFE_DIVIDE(DATE_DIFF(COALESCE(`Termination Effective Date`,CURRENT_DATE()),PARSE_DATE('%d-%b-%Y',CONCAT(`Anniversary Effective Date`,"-",`Original Year`)), MONTH),12) AS YEARS_ACTIVE
    ,IF(UPPER(`Easy Pay`) = 'ENROLLED IN EZPAY',1,0) AS EZ_PAY
    ,IF(UPPER(`Marital Status`) = 'MARRIED',1,0) AS MARRIED
    ,IF(UPPER(`Marital Status`) = 'WIDOWED',1,0) AS WIDOWED
    ,IF(UPPER(`Marital Status`) IN ('SEPARATED','DIVORCED'),1,0) AS DIVORCED
    ,IF(UPPER(`Marital Status`) = 'SINGLE',1,0) AS SINGLE
    ,IF(UPPER(`Marital Status`) = 'UNKNOWN',1,0) AS UNKNOWN
    ,CAST(`My Account` AS INT64) AS ONLINE_ACCT
    ,IF(UPPER(PACKAGE) LIKE '%PROTECTION%',1,0) AS ACCIDENT_FORGIVE
    ,CAST(`Multiple Policy Discount` AS INT64) AS MULTIPOLICY
    ,IF(UPPER(`Account Type`) LIKE 'SERVICE%',1,0) AS SERVICE_ACCT
    ,IF(UPPER(`Account Type`) LIKE 'AGENT%',1,0) AS AGENT_ACCT
    ,IF(UPPER(`Account Type`) LIKE 'REQUESTED%',1,0) AS REQUESTED_ACCT
  FROM `couch2coding.CLAIMS_CASESTUDY.CLAIM_DETAIL` ---THIS IS CLAIM DETAIL BUT LOOKS MORE LIKE POLICY ACCOUNT DTL
  WHERE UPPER(`Line Code`) LIKE '%AUTO%'
)

,STAGE AS
(
  SELECT *
    ,IF(ACCD_DT IS NULL,0,1) AS HAS_ACCIDENT
    ,SAFE_DIVIDE(DATE_DIFF(ACCD_DT,START_DT, MONTH),12) AS YRS_TILL_FIRST_CLAIM
  FROM POLICY_HOLDERS AS P
  LEFT JOIN 
    (
      SELECT `Policy Number` AS POLICY_NBR
        -- ,`Claim Number` AS CLAIM_NBR
        ,MIN(`Accident Date`) AS ACCD_DT --WHEN WAS THE FIRST TIME THE PERSON FILED A CLAIM
        --$$ AMOUNT IS STRING FORMAT LIKE $10.94 & ($90.22) FOR NEGATIVE
        --DEPENDING ON PATTERN WE MAKE NUMBER POSITIVE OR NEGATIVE AFTER CONVERTING TO FLOAT
        ,SUM
          (
            CASE 
              WHEN `Adjusted Paid Losses` LIKE '(%' 
                THEN 
                  -1 * CAST(REGEXP_REPLACE(`Adjusted Paid Losses`, r'[\$,()]', '') AS FLOAT64)
              ELSE 
                CAST(REGEXP_REPLACE(`Adjusted Paid Losses`, r'[\$,]', '') AS FLOAT64)
            END
          ) AS PAID_OUT
      FROM `couch2coding.CLAIMS_CASESTUDY.POLICY_DETAILS`
      GROUP BY ALL
    )
    USING(POLICY_NBR)
)

SELECT * EXCEPT(POLICY_NBR)
  ,RANK() OVER(ORDER BY POLICY_NBR) AS POLICY_NBR_SCRUB
FROM STAGE